import type { ComponentDefinition } from "../types/components";

/** Available electronic components for the palette */
export const COMPONENTS: ComponentDefinition[] = [
  // Basic
  {
    id: "resistor",
    name: "Resistor",
    category: "basic",
    description: "Limits current flow (220 Ω)",
    icon: "⊟",
    wokwiTag: "wokwi-resistor",
    inputs: 1,
    outputs: 1,
  },
  {
    id: "led",
    name: "LED Red",
    category: "basic",
    description: "Red Light Emitting Diode",
    icon: "🔴",
    wokwiTag: "wokwi-led",
    inputs: 1,
    outputs: 1,
  },
  {
    id: "led-green",
    name: "LED Green",
    category: "basic",
    description: "Green Light Emitting Diode",
    icon: "🟢",
    wokwiTag: "wokwi-led",
    inputs: 1,
    outputs: 1,
  },
  {
    id: "led-blue",
    name: "LED Blue",
    category: "basic",
    description: "Blue Light Emitting Diode",
    icon: "🔵",
    wokwiTag: "wokwi-led",
    inputs: 1,
    outputs: 1,
  },
  {
    id: "led-yellow",
    name: "LED Yellow",
    category: "basic",
    description: "Yellow Light Emitting Diode",
    icon: "🟡",
    wokwiTag: "wokwi-led",
    inputs: 1,
    outputs: 1,
  },
  {
    id: "rgb-led",
    name: "RGB LED",
    category: "basic",
    description: "Common Cathode RGB LED",
    icon: "🌈",
    wokwiTag: "wokwi-rgb-led",
    inputs: 4,
    outputs: 0,
  },
  {
    id: "neopixel",
    name: "NeoPixel",
    category: "basic",
    description: "WS2812B Addressable LED",
    icon: "✨",
    wokwiTag: "wokwi-neopixel",
    inputs: 1,
    outputs: 1,
  },
  {
    id: "pushbutton",
    name: "Push Button",
    category: "basic",
    description: "Momentary Push Button",
    icon: "🔘",
    wokwiTag: "wokwi-pushbutton",
    inputs: 2,
    outputs: 2,
  },
  {
    id: "slide-switch",
    name: "Slide Switch",
    category: "basic",
    description: "SPDT Slide Switch",
    icon: "⏚",
    wokwiTag: "wokwi-slide-switch",
    inputs: 3,
    outputs: 0,
  },
  {
    id: "potentiometer",
    name: "Potentiometer",
    category: "basic",
    description: "10 kΩ Variable Resistor",
    icon: "🎛️",
    wokwiTag: "wokwi-potentiometer",
    inputs: 3,
    outputs: 0,
  },
  {
    id: "buzzer",
    name: "Buzzer",
    category: "basic",
    description: "Active Buzzer, 5V",
    icon: "🔊",
    wokwiTag: "wokwi-buzzer",
    inputs: 2,
    outputs: 0,
  },
  {
    id: "relay",
    name: "Relay",
    category: "basic",
    description: "5V SPDT Relay",
    icon: "🔌",
    wokwiTag: "wokwi-ks2e-m-dc5",
    inputs: 5,
    outputs: 0,
  },
  {
    id: "capacitor",
    name: "Capacitor",
    category: "basic",
    description: "100 nF Capacitor",
    icon: "⊞",
    inputs: 1,
    outputs: 1,
  },
  {
    id: "breadboard",
    name: "Breadboard",
    category: "basic",
    description: "Full Size Breadboard",
    icon: "⌨️",
    inputs: 0,
    outputs: 0,
  },
  {
    id: "breadboard-half",
    name: "Breadboard Half",
    category: "basic",
    description: "Half Size Breadboard",
    icon: "⌨️",
    inputs: 0,
    outputs: 0,
  },

  // ICs / MCUs
  {
    id: "arduino-uno",
    name: "Arduino Uno",
    category: "ic",
    description: "ATmega328P Microcontroller Board",
    icon: "🖥️",
    wokwiTag: "wokwi-arduino-uno",
    inputs: 14,
    outputs: 14,
  },
  {
    id: "arduino-nano",
    name: "Arduino Nano",
    category: "ic",
    description: "Compact ATmega328P Board",
    icon: "📱",
    wokwiTag: "wokwi-arduino-nano",
    inputs: 14,
    outputs: 14,
  },
  {
    id: "arduino-mega",
    name: "Arduino Mega",
    category: "ic",
    description: "ATmega2560 Board",
    icon: "🏗️",
    wokwiTag: "wokwi-arduino-mega",
    inputs: 54,
    outputs: 54,
  },
  {
    id: "esp32",
    name: "ESP32",
    category: "ic",
    description: "ESP32 DevKit V1",
    icon: "📡",
    wokwiTag: "wokwi-esp32-devkit-v1",
    inputs: 30,
    outputs: 30,
  },

  // Display
  {
    id: "7seg",
    name: "7-Segment",
    category: "output",
    description: "Common Cathode 7-Segment Display",
    icon: "8️⃣",
    wokwiTag: "wokwi-7segment",
    inputs: 8,
    outputs: 0,
  },
  {
    id: "lcd-16x2",
    name: "LCD 16×2",
    category: "output",
    description: "HD44780 16x2 Character LCD",
    icon: "📟",
    wokwiTag: "wokwi-lcd1602",
    inputs: 16,
    outputs: 0,
  },
  {
    id: "lcd-20x4",
    name: "LCD 20×4",
    category: "output",
    description: "HD44780 20x4 Character LCD",
    icon: "📟",
    wokwiTag: "wokwi-lcd2004",
    inputs: 16,
    outputs: 0,
  },
  {
    id: "ssd1306",
    name: "OLED SSD1306",
    category: "output",
    description: "128×64 I2C OLED Display",
    icon: "📺",
    wokwiTag: "wokwi-ssd1306",
    inputs: 4,
    outputs: 0,
  },
  {
    id: "neopixel-matrix",
    name: "NeoPixel Matrix",
    category: "output",
    description: "8×8 WS2812 RGB Matrix",
    icon: "⬛",
    wokwiTag: "wokwi-neopixel-matrix",
    inputs: 1,
    outputs: 1,
  },
  {
    id: "led-bar-graph",
    name: "LED Bar Graph",
    category: "output",
    description: "10 Segment LED Bar Graph",
    icon: "📊",
    wokwiTag: "wokwi-led-bar-graph",
    inputs: 10,
    outputs: 0,
  },

  // Sensors
  {
    id: "hcsr04",
    name: "Ultrasonic",
    category: "input",
    description: "HC-SR04 Ultrasonic Distance Sensor",
    icon: "📏",
    wokwiTag: "wokwi-hc-sr04",
    inputs: 4,
    outputs: 0,
  },
  {
    id: "dht22",
    name: "Temp / Humidity",
    category: "input",
    description: "DHT22 Temperature & Humidity Sensor",
    icon: "🌡️",
    wokwiTag: "wokwi-dht22",
    inputs: 4,
    outputs: 0,
  },
  {
    id: "pir",
    name: "PIR Motion",
    category: "input",
    description: "HC-SR501 PIR Motion Sensor",
    icon: "🏃",
    wokwiTag: "wokwi-pir-motion-sensor",
    inputs: 3,
    outputs: 0,
  },
  {
    id: "ir-recv",
    name: "IR Receiver",
    category: "input",
    description: "TSOP38238 IR Receiver",
    icon: "📡",
    wokwiTag: "wokwi-ir-receiver",
    inputs: 3,
    outputs: 0,
  },
  {
    id: "ir-remote",
    name: "IR Remote",
    category: "input",
    description: "21-key IR Remote Control",
    icon: "🎮",
    wokwiTag: "wokwi-ir-remote",
    inputs: 0,
    outputs: 1,
  },
  {
    id: "ntc-sensor",
    name: "NTC Temp Sensor",
    category: "input",
    description: "Analog Thermistor",
    icon: "🌡️",
    wokwiTag: "wokwi-ntc-temperature-sensor",
    inputs: 2,
    outputs: 0,
  },
  {
    id: "flame-sensor",
    name: "Flame Sensor",
    category: "input",
    description: "Infrared Flame Sensor",
    icon: "🔥",
    wokwiTag: "wokwi-flame-sensor",
    inputs: 4,
    outputs: 0,
  },
  {
    id: "gas-sensor",
    name: "Gas Sensor",
    category: "input",
    description: "MQ-2 Gas Sensor Module",
    icon: "🌫️",
    wokwiTag: "wokwi-gas-sensor",
    inputs: 4,
    outputs: 0,
  },
  {
    id: "photoresistor-sensor",
    name: "Photoresistor",
    category: "input",
    description: "LDR Module",
    icon: "☀️",
    wokwiTag: "wokwi-photoresistor-sensor",
    inputs: 4,
    outputs: 0,
  },
  {
    id: "sound-sensor",
    name: "Sound Sensor",
    category: "input",
    description: "Analog Sound Sensor",
    icon: "🎤",
    wokwiTag: "wokwi-small-sound-sensor",
    inputs: 4,
    outputs: 0,
  },
  {
    id: "mpu6050",
    name: "MPU6050",
    category: "input",
    description: "Accelerometer & Gyroscope",
    icon: "🧭",
    wokwiTag: "wokwi-mpu6050",
    inputs: 8,
    outputs: 0,
  },

  // Actuators
  {
    id: "servo",
    name: "Servo Motor",
    category: "output",
    description: "SG90 180° Servo",
    icon: "⚙️",
    wokwiTag: "wokwi-servo",
    inputs: 3,
    outputs: 0,
  },
  {
    id: "stepper-motor",
    name: "Stepper Motor",
    category: "output",
    description: "NEMA 17 Stepper Motor",
    icon: "🔄",
    wokwiTag: "wokwi-stepper-motor",
    inputs: 4,
    outputs: 0,
  },
  {
    id: "analog-joystick",
    name: "Analog Joystick",
    category: "input",
    description: "XY Joystick + Button",
    icon: "🕹️",
    wokwiTag: "wokwi-analog-joystick",
    inputs: 5,
    outputs: 0,
  },
  {
    id: "rotary-encoder",
    name: "Rotary Encoder",
    category: "input",
    description: "KY-040 Rotary Encoder",
    icon: "🔘",
    wokwiTag: "wokwi-ky-040",
    inputs: 5,
    outputs: 0,
  },
  {
    id: "membrane-keypad",
    name: "Membrane Keypad",
    category: "input",
    description: "4×4 Matrix Keypad",
    icon: "⌨️",
    wokwiTag: "wokwi-membrane-keypad",
    inputs: 8,
    outputs: 0,
  },
  {
    id: "dip-switch-8",
    name: "DIP Switch (8)",
    category: "input",
    description: "8-Position DIP Switch",
    icon: " schak",
    wokwiTag: "wokwi-dip-switch-8",
    inputs: 8,
    outputs: 8,
  },

  // Modules
  {
    id: "ds1307",
    name: "RTC DS1307",
    category: "ic",
    description: "Real-Time Clock Module",
    icon: "⏰",
    wokwiTag: "wokwi-ds1307",
    inputs: 4,
    outputs: 0,
  },
  {
    id: "hx711",
    name: "HX711",
    category: "ic",
    description: "Load Cell Amplifier",
    icon: "⚖️",
    wokwiTag: "wokwi-hx711",
    inputs: 6,
    outputs: 0,
  },
  {
    id: "microsd",
    name: "MicroSD Card",
    category: "ic",
    description: "SPI SD Card Module",
    icon: "💾",
    wokwiTag: "wokwi-microsd-card",
    inputs: 6,
    outputs: 0,
  },
];
